### PR TITLE
`[s3/ls]` Handle buckets w/ >1000 items

### PR DESCRIPTION
**Pull request by harold**
- https://github.com/mcohen01/amazonica/commit/edc45ec278a7808d2a408f9ccac2c8ddb7177fbc
 - Had a bucket go over 1000 items this week, and `ls` did not list all items

### CODE REVIEW

**Review by cnuernber — APPROVED** [review]
I recommend also upgrading to latest tech.io.  Do you want to release this or do you want me to release it?

**Comment by harold** [comment]
> Do you want to release this or do you want me to release it?
>

Go for it, thank you!

> I recommend also upgrading to latest tech.io. 
>

What do you think about not specifying an explicit `tech.io` dep in the app I'm working on? Instead just specifying the latest of `tech.io.aws` and letting that pull `tech.io` transitively?

**Comment by cnuernber** [comment]
I meant as part of the next release.  I think pulling tech.io transitively is wise.

**Comment by harold** [comment]
I did it!

https://clojars.org/techascent/tech.io.aws

https://github.com/techascent/tech.io.aws/commit/5154f462ae6f62778b010f552b2de18ca07ec5dd

Thanks! (:

**Pull request merged**
